- README.md
- erd.dbml
* 저희 프로젝트 필요한 db schema 구조 정리했습니다. 
* 인덱스와 상세한 타입은 픽스되지 않았습니다. (디자인기획 확정 이후 업데이트 필요)
* users-groups (N:N)
* users-cards (1:N)
* users-introductions (1:N)
* users-favorites(N:N)
* cards(from_user_name, to_user_name): 중복 데이터이지만, 불필요한 조인을 없애기 위해서 추가했습니다. 피드백 부탁드립니다. 
================2024-01-17================
* [introductions] table 내 column 추가 (nickname, profile_image_url)
* [introductions_questions] table 내 필드 설명
* type 필드: "관심사", "커스텀" 값을 가질 수 있다. 그룹장이 커스텀 질문을 올리면 해당 타입으로 사용한다. 
* question: 질문 내용
* has_selections: 선택지가 있는 경우
* answers: 유저 선택 또는 입력한 답변
Close #이슈번호
> [ERD] db scheam 작성

- src/main/java/com/wable/harmonika/HarmonikaApplication.java
- src/main/java/com/wable/harmonika/domain/user/dto/MyUserResDto.java
- src/main/java/com/wable/harmonika/global/entity/BaseTimeEntity.java
- erd와 필드명 통일
- @EnableJpaAuditing 추가
Close #이슈번호
> 필드명 erd 맞추기 및 @EnableJpaAuditing 추가

- build.gradle
- src/main/java/com/wable/harmonika/global/config/Swagger3Configuration.java
* 화면이 안나와서 스웨거에 대한 라이브러리 변경 했습니다
* 이게 맞는지 모르겠는데 Swagger 3 버전 쓰고있는듯 합니다
* http://localhost:8080/swagger-ui/index.html 들어가면 볼 수 있음
Close #이슈번호
> Swagger http://localhost:8080/swagger-ui/index.html 추가

- build.gradle
- src/main/generated/com/wable/harmonika/domain/card/entity/QCards.java
- src/main/generated/com/wable/harmonika/domain/group/entity/QGroupQuestion.java
- src/main/generated/com/wable/harmonika/domain/group/entity/QGroups.java
- src/main/generated/com/wable/harmonika/domain/group/entity/QQuestions.java
- src/main/generated/com/wable/harmonika/domain/group/entity/QUserGroups.java
- src/main/generated/com/wable/harmonika/domain/profile/entity/QProfileQuestions.java
- src/main/generated/com/wable/harmonika/domain/profile/entity/QProfiles.java
- src/main/generated/com/wable/harmonika/domain/user/entity/QUsers.java
- src/main/generated/com/wable/harmonika/global/entity/QBaseTimeEntity.java
- src/main/java/com/wable/harmonika/domain/card/api/CardController.java
- src/main/java/com/wable/harmonika/domain/card/dto/CardsRequest.java
- src/main/java/com/wable/harmonika/domain/card/dto/CardsResponse.java
- src/main/java/com/wable/harmonika/domain/card/dto/ListCardsRequest.java
- src/main/java/com/wable/harmonika/domain/card/dto/UpdateCardsRequest.java
- src/main/java/com/wable/harmonika/domain/card/entity/Cards.java
- src/main/java/com/wable/harmonika/domain/card/repository/CardRepository.java
- src/main/java/com/wable/harmonika/domain/card/repository/CardRepositoryCustom.java
- src/main/java/com/wable/harmonika/domain/card/repository/impl/CardRepositoryImpl.java
- src/main/java/com/wable/harmonika/domain/card/service/CardService.java
- src/main/java/com/wable/harmonika/domain/card/service/impl/CardServiceImpl.java
- src/main/java/com/wable/harmonika/domain/group/entity/Groups.java
- src/main/java/com/wable/harmonika/domain/user/api/UserController.java
- src/main/java/com/wable/harmonika/global/auth/UserArgumentResolver.java
- src/main/java/com/wable/harmonika/global/config/QueryDSLConfig.java
- src/main/java/com/wable/harmonika/global/config/WebConfig.java
- src/main/java/com/wable/harmonika/global/security/SecurityConfig.java
- src/main/resources/application-dev.yml
- src/test/java/com/wable/harmonika/domain/card/repository/CardRepositoryTest.java
임시 카드 도메인 API PR입니다. 
Close #이슈번호
> [Feat/card] 임시 카드 도메인 API 

- src/main/generated/com/wable/harmonika/domain/user/entity/QUsers.java
- src/main/java/com/wable/harmonika/domain/profile/api/ProfileController.java
- src/main/java/com/wable/harmonika/domain/profile/service/ProfileService.java
- src/main/java/com/wable/harmonika/global/config/AWSS3Config.java
* 인젝션 에러로 s3 presigned url 관련 api 미완성된 부분 주석 처리
Close #이슈번호
> "[fix/s3-env] s3 환경변수 주입 에러로 주석처리"

- src/main/resources/application-dev.yml
> [FEAT/APPLICATION-CONFIG]: spring 하위에 jpa 추가

- src/main/java/com/wable/harmonika/domain/card/api/CardController.java
- src/main/java/com/wable/harmonika/domain/card/entity/Cards.java
- src/main/java/com/wable/harmonika/domain/group/GroupService.java
- src/main/java/com/wable/harmonika/domain/group/entity/Groups.java
- src/main/java/com/wable/harmonika/domain/group/entity/UserGroups.java
- src/main/java/com/wable/harmonika/domain/profile/entity/ProfileQuestions.java
- src/main/java/com/wable/harmonika/domain/profile/entity/Profiles.java
- src/main/java/com/wable/harmonika/domain/user/dto/MyUserResDto.java
- src/main/java/com/wable/harmonika/domain/user/dto/SignUpReqDto.java
- src/main/java/com/wable/harmonika/domain/user/entity/Users.java
- src/main/java/com/wable/harmonika/domain/user/repository/UserRepository.java
- src/main/java/com/wable/harmonika/domain/user/service/UserService.java
- src/main/java/com/wable/harmonika/global/auth/AwsCognitoJwtParserUtil.java
- src/main/java/com/wable/harmonika/global/auth/AwsCognitoJwtValidatorUtil.java
- src/main/java/com/wable/harmonika/global/auth/UserArgumentResolver.java
- src/main/java/com/wable/harmonika/global/auth/VerifyToken.java
- src/main/java/com/wable/harmonika/global/config/WebConfig.java
- src/main/java/com/wable/harmonika/global/error/ErrorHandler.java
- src/main/java/com/wable/harmonika/global/error/exception/ForbiddenException.java
- src/main/java/com/wable/harmonika/global/error/exception/UnauthorizedException.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
* 아래와 같이 토큰 유효성 검증합니다. 
Close #이슈번호
> [Feat/auth] 토큰 유효성 검증 (draft)

- src/main/java/com/wable/harmonika/domain/card/api/CardController.java
- src/main/java/com/wable/harmonika/domain/card/dto/CardsRequest.java
- src/main/java/com/wable/harmonika/domain/card/entity/Cards.java
- src/main/java/com/wable/harmonika/domain/card/service/CardService.java
- src/main/java/com/wable/harmonika/domain/card/service/impl/CardServiceImpl.java
- src/main/java/com/wable/harmonika/domain/group/GroupController.java
- src/main/java/com/wable/harmonika/domain/group/GroupService.java
- src/main/java/com/wable/harmonika/domain/profile/api/ProfileController.java
- src/main/java/com/wable/harmonika/domain/user/api/UserController.java
- src/main/java/com/wable/harmonika/domain/user/dto/SignUpReqDto.java
- src/main/java/com/wable/harmonika/domain/user/entity/Users.java
- src/main/java/com/wable/harmonika/domain/user/repository/UserRepository.java
- src/main/java/com/wable/harmonika/domain/user/service/UserService.java
- src/main/java/com/wable/harmonika/global/auth/UserArgumentResolver.java
- src/main/java/com/wable/harmonika/global/auth/VerifyToken.java
* argument resolver 로 token 확인하여 Users 데이터 생성
* 모든 controller 인풋 파라미터에 Users 추가
Close #이슈번호
> [Feat/auth] argument resolver 마무리

- build.gradle
> [FIX/BUILDGRADLE]: 쿼리DSL 파일 위치 수정

- src/main/java/com/wable/harmonika/domain/profile/api/ProfileController.java
* 하나의 엔드포인트에서 내 프로필, 다른 그룹 프로필, 다른 사람 프로필에서 분리함
* 내 프로필 조회
* 내 그룹 프로필 및 다른 사람 프로필 조회로 수정
* targetUserId 으로 네이밍 수정
Close #이슈번호
> 2. Feat/profile update

- src/main/java/com/wable/harmonika/domain/card/api/CardController.java
- src/main/java/com/wable/harmonika/domain/card/dto/ListCardsByGroupRequest.java
- src/main/java/com/wable/harmonika/domain/group/api/GroupController.java
- src/main/java/com/wable/harmonika/domain/profile/api/ProfileController.java
- src/main/java/com/wable/harmonika/domain/user/api/UserController.java
* 스웨거 태그 수정합니다. 
* 카드, 그룹, 유저
* GET 요청 query string을 일일이 적으라는데 번거롭네요
https://github.com/springdoc/springdoc-openapi/issues/268
Close #이슈번호
> [fix/swagger] 스웨거 태그 분류

- build.gradle
- src/main/java/com/wable/harmonika/domain/card/dto/CardsDto.java
- src/main/java/com/wable/harmonika/domain/profile/api/ProfileController.java
- src/main/java/com/wable/harmonika/domain/profile/dto/QuestionDataDto.java
- src/main/java/com/wable/harmonika/domain/profile/dto/UpdateProfileDto.java
- src/main/java/com/wable/harmonika/domain/profile/entity/ProfileQuestions.java
- src/main/java/com/wable/harmonika/domain/profile/repository/ProfileCustomRepositoryImpl.java
- src/main/java/com/wable/harmonika/domain/profile/repository/ProfileQuestionsCustomRepositoryImpl.java
- src/main/java/com/wable/harmonika/domain/profile/service/ProfileService.java
* 프로필 업데이트 엔드포인트 분리
* 스웨거 추가
Close #이슈번호
> [FEAT/PROFILE_UPDATE]: 프로필 업데이트 엔드포인트 분리

- src/main/java/com/wable/harmonika/global/auth/AwsCognitoJwtValidatorUtil.java
- src/main/java/com/wable/harmonika/global/auth/UserArgumentResolver.java
- src/main/java/com/wable/harmonika/global/auth/VerifyToken.java
- src/main/resources/application-dev.yml
- src/main/resources/application.yml
> [Feat/auth] 임시 토큰 검증 제거

- src/main/java/com/wable/harmonika/global/config/WebConfig.java
> [feat/cors] cors 허용

- src/main/java/com/wable/harmonika/global/auth/AwsCognitoJwtParserUtil.java
- src/main/resources/application.yml
* commit 잘못 들어간거 수정합니다. 
Close #이슈번호
> [fix/auth] getClaim rollback

- src/main/java/com/wable/harmonika/domain/profile/api/ProfileController.java
- src/main/java/com/wable/harmonika/domain/profile/service/ProfileService.java
> [FIX/S3]: 수정하

- src/main/java/com/wable/harmonika/domain/profile/api/ProfileController.java
> [FEAT/PROFILE_ME]: 프로필 조회에 groupId 필터 추가

- src/main/java/com/wable/harmonika/domain/card/api/CardController.java
- src/main/java/com/wable/harmonika/domain/card/dto/ListCardsResponse.java
- src/main/java/com/wable/harmonika/domain/card/repository/CardRepositoryCustom.java
- src/main/java/com/wable/harmonika/domain/card/repository/impl/CardRepositoryImpl.java
- src/main/java/com/wable/harmonika/domain/card/service/CardService.java
- src/main/java/com/wable/harmonika/domain/card/service/impl/CardServiceImpl.java
- src/main/java/com/wable/harmonika/global/auth/UserArgumentResolver.java
- src/main/java/com/wable/harmonika/global/config/WebConfig.java
* 프론트 페이지 계산을 위해 count 추가
* 리졸버 유저 가져오기
Close #이슈번호
> [feat/card-pagination] 카드 총 갯수 조회 && 리졸버에서 유저 가져오기

- src/main/java/com/wable/harmonika/domain/profile/api/ProfileController.java
- src/main/java/com/wable/harmonika/domain/profile/dto/QuestionDataDto.java
- src/main/java/com/wable/harmonika/domain/profile/dto/UpdateProfileDto.java
- src/main/java/com/wable/harmonika/domain/profile/repository/ProfileQuestionsCustomRepository.java
- src/main/java/com/wable/harmonika/domain/profile/repository/impl/ProfileQuestionsRepositoryImpl.java
> [FIX/PROFILE_UPDATE]: DTO 수정

- src/main/java/com/wable/harmonika/domain/group/api/GroupController.java
- src/main/java/com/wable/harmonika/domain/group/entity/Groups.java
- src/main/java/com/wable/harmonika/domain/group/repository/GroupRepository.java
- src/main/java/com/wable/harmonika/domain/group/service/GroupService.java
- src/main/java/com/wable/harmonika/global/error/Error.java
> [FIX/GROUP_ENTITY]: group 에 unique=true 추가

- src/main/java/com/wable/harmonika/global/auth/UserArgumentResolver.java
- src/main/java/com/wable/harmonika/global/auth/VerifyToken.java
- src/main/java/com/wable/harmonika/global/config/WebConfig.java
* cognito clientId, issuerUri 환경변수로 받기
Close #이슈번호
> [fix/env] 환경변수로 받기

- src/main/java/com/wable/harmonika/domain/profile/dto/CreateProfileByGroupDto.java
- src/main/java/com/wable/harmonika/domain/profile/dto/CreateProfileByUserDto.java
- src/main/java/com/wable/harmonika/domain/profile/dto/GetProfileResponseDto.java
- src/main/java/com/wable/harmonika/domain/profile/dto/UpdateProfileDto.java
- src/main/java/com/wable/harmonika/domain/profile/service/ProfileService.java
> field 오류 수정

- src/main/java/com/wable/harmonika/domain/card/dto/CardsDto.java
- src/main/java/com/wable/harmonika/domain/card/service/impl/CardServiceImpl.java
* dto field type 추가
Close #이슈번호
> [fix/card] dto field type 추가
